name: Javascript CI
on:
  push:
    branches:
      - master
    paths:
      - .github/**
      - javascript/**
  pull_request:
    branches:
      - master
    paths:
      - .github/**
      - javascript/**
  schedule:
    - cron:  '* 4 * * *'
defaults:
  run:
    working-directory: javascript
jobs:
  Build_Javascript_Client:
    name: Build JavaScript Client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm pack
      - name: Get project version
        run: echo "PROJECT_VERSION=$(head -n 5 package.json |grep "version"|cut -d "\"" -f4)" >> $GITHUB_ENV
      - name: Deploy SockJS EventBus Client to NPM
        if: ${{ github.repository_owner == 'vert-x3' && github.event_name == 'push' && !endsWith(env.PROJECT_VERSION, '-SNAPSHOT') }}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          check-version: true
          package: javascript/package.json
          access: public